name: daily_planner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  analog_clock_picker: ^0.0.6
  animated_bottom_navigation_bar: ^1.3.3
  awesome_snackbar_content: ^0.1.4
  email_validator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_event_calendar: ^1.0.0
  flutter_localization: ^0.2.2
  flutter_staggered_animations: ^1.1.1
  flutter_time_picker_spinner: ^2.0.0
  icons_flutter: ^0.0.4
  intl: ^0.19.0
  loading_animation_widget: ^1.2.1
  password_strength: ^0.2.0
  password_strength_checker: ^1.2.4
  path: ^1.9.0
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3+1
  syncfusion_flutter_calendar: ^27.1.50
  time_picker_spinner: ^1.0.0
  time_planner: ^0.1.2+1
  video_player: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
  - assets/
  uses-material-design: true
